version: "3"
services:
    db-container:
        image: busybox
        volumes:
            - db-volume:/var/lib/mysql/
    db:
        container_name: django_mysql
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: dbpass01
            MYSQL_DATABASE: django
            MYSQL_USER: django
            MYSQL_PASSWORD: django
        volumes:
            - db-container
            - ./mysql-confd/my.cnf:/etc/mysql/conf.d/my.cnf
        ports:
            - 3306:3306
        depends_on:
            - db-container
        restart: always
    pma-container:
        container_name: php_myadmin
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_HOST=db
            - PMA_USER=root
            - PMA_PASSWORD=dbpass01
        ports:
            - 8080:80
        depends_on:
            - db
        restart: always
    rest_api:
        container_name: django_rest_api
        build:
            context: .
            dockerfile: DockerfilePython
        volumes:
            - ./code/rest_api:/code
        tty: true
        ports:
            - 8000:8000
        depends_on:
            - db
        restart: always
        environment:
            - DB_NAME=django
            - DB_USER=django
            - DB_PASSWORD=django
            - DB_HOST=db
            - DB_PORT=3306
    web_front:
        container_name: react_web_front
        build:
            context: .
            dockerfile: DockerfileNode
        volumes:
            - ./code/web_front:/code
        tty: true
        ports:
            - 3000:3000
        depends_on:
            - rest_api
        restart: always
volumes:
    db-volume:
